# Generated by Django 4.1.5 on 2023-01-07 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viryaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uregmodel',
            new_name='dmodel',
        ),
        migrations.RenameField(
            model_name='dmodel',
            old_name='uname',
            new_name='username',
        ),
    ]
