# Generated by Django 4.1.5 on 2023-01-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viryaapp', '0002_rename_uregmodel_dmodel_rename_uname_dmodel_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='orthomodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='static')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=30)),
                ('specialisation', models.CharField(max_length=30)),
            ],
        ),
    ]
