# Generated by Django 4.1.5 on 2023-01-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viryaapp', '0003_orthomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orthomodel',
            name='image',
            field=models.FileField(upload_to='static/'),
        ),
    ]
