# Generated by Django 4.1.5 on 2023-01-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viryaapp', '0004_alter_orthomodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orthomodel',
            name='image',
            field=models.FileField(upload_to='viryaapp/static/'),
        ),
    ]
